BEGIN;
SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='120s';
ALTER TABLE public.transfer_jobs ADD COLUMN IF NOT EXISTS recovery_next_attempt_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS recovery_backoff_seconds INTEGER NOT NULL DEFAULT 30, ADD COLUMN IF NOT EXISTS recovery_manual_review BOOLEAN NOT NULL DEFAULT false, ADD COLUMN IF NOT EXISTS recovery_last_error TEXT, ADD COLUMN IF NOT EXISTS recovery_last_error_at TIMESTAMPTZ;
ALTER TABLE public.transfer_jobs DROP CONSTRAINT IF EXISTS transfer_jobs_recovery_backoff_check;
ALTER TABLE public.transfer_jobs ADD CONSTRAINT transfer_jobs_recovery_backoff_check CHECK(recovery_backoff_seconds BETWEEN 1 AND 86400);
CREATE INDEX IF NOT EXISTS idx_jobs_upload_recovery_due ON public.transfer_jobs(recovery_next_attempt_at,created_at,id) WHERE saga_version=1 AND direction='upload' AND status IN('telegram_succeeded','compensation_pending') AND recovery_manual_review=false;
CREATE OR REPLACE FUNCTION public.claim_upload_saga_recovery(p_node_id TEXT,p_node_token TEXT,p_limit INTEGER) RETURNS TABLE(tenant_id UUID,job_id UUID,correlation_id UUID,status TEXT,attempt_token UUID,telegram_message_id BIGINT,storage_peer_id BIGINT,storage_peer_kind TEXT,telegram_file_id TEXT,telegram_file_name TEXT,telegram_file_size BIGINT,telegram_mime_type TEXT,receipt_recorded_at TIMESTAMPTZ,requested_folder_id BIGINT,source_ref TEXT,transport_mode TEXT,target TEXT) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
BEGIN
 PERFORM public.authenticate_saga_node(p_node_id,p_node_token,false,false);
 IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'recovery claim limit must be between 1 and 100' USING ERRCODE='22023'; END IF;
 UPDATE public.transfer_jobs j SET recovery_manual_review=true,recovery_last_error=COALESCE(j.recovery_last_error,'maximum recovery attempts exhausted'),recovery_last_error_at=COALESCE(j.recovery_last_error_at,now()),attempt_token=NULL,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE j.saga_version=1 AND j.direction='upload' AND j.request_spec->>'staging_node_id'=p_node_id AND j.status IN('telegram_succeeded','compensation_pending') AND NOT j.recovery_manual_review AND j.reconcile_attempt_count>=j.max_attempts;
 RETURN QUERY WITH claimable AS (SELECT c.id FROM public.transfer_jobs c WHERE c.saga_version=1 AND c.direction='upload' AND c.request_spec->>'staging_node_id'=p_node_id AND c.status IN('telegram_succeeded','compensation_pending') AND NOT c.recovery_manual_review AND c.reconcile_attempt_count<c.max_attempts AND COALESCE(c.recovery_next_attempt_at,c.next_attempt_at,'-infinity'::timestamptz)<=now() AND (c.attempt_token IS NULL OR c.lease_owner IS NULL OR c.lease_expires_at IS NULL OR c.lease_expires_at<=now()) ORDER BY COALESCE(c.recovery_next_attempt_at,c.next_attempt_at,'-infinity'::timestamptz),c.created_at,c.id FOR UPDATE SKIP LOCKED LIMIT p_limit) UPDATE public.transfer_jobs j SET attempt_token=gen_random_uuid(),lease_owner='recovery:'||p_node_id,lease_expires_at=now()+interval '5 minutes',reconcile_attempt_count=j.reconcile_attempt_count+1,last_reconciled_at=now(),recovery_next_attempt_at=NULL,updated_at=now() FROM claimable WHERE j.id=claimable.id RETURNING j.tenant_id,j.id,j.correlation_id,j.status,j.attempt_token,j.telegram_message_id,j.storage_peer_id,j.storage_peer_kind,j.telegram_file_id,j.telegram_file_name,j.telegram_file_size,j.telegram_mime_type,j.receipt_recorded_at,j.requested_folder_id,j.request_spec->>'source_ref',j.request_spec->>'transport_mode',j.request_spec->>'target';
END $$;
CREATE OR REPLACE FUNCTION public.renew_upload_saga_recovery(p_node_id TEXT,p_node_token TEXT,p_job_id UUID,p_attempt_token UUID,p_lease_seconds INTEGER DEFAULT 300) RETURNS TIMESTAMPTZ LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ DECLARE renewed TIMESTAMPTZ; BEGIN PERFORM public.authenticate_saga_node(p_node_id,p_node_token,false,true); IF p_job_id IS NULL OR p_attempt_token IS NULL OR p_lease_seconds NOT BETWEEN 30 AND 900 THEN RAISE EXCEPTION 'invalid recovery lease renewal request' USING ERRCODE='22023'; END IF; UPDATE public.transfer_jobs j SET lease_expires_at=now()+make_interval(secs=>p_lease_seconds),updated_at=now() WHERE j.id=p_job_id AND j.saga_version=1 AND j.direction='upload' AND j.request_spec->>'staging_node_id'=p_node_id AND j.lease_owner='recovery:'||p_node_id AND j.attempt_token=p_attempt_token AND j.lease_expires_at>now() RETURNING j.lease_expires_at INTO renewed; IF NOT FOUND THEN RAISE EXCEPTION 'recovery lease is missing, expired, or fenced' USING ERRCODE='40001'; END IF; RETURN renewed; END $$;
CREATE OR REPLACE FUNCTION public.release_upload_saga_recovery(p_node_id TEXT,p_node_token TEXT,p_job_id UUID,p_attempt_token UUID,p_outcome TEXT,p_error TEXT DEFAULT NULL) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ DECLARE attempts INTEGER; allowed INTEGER; base INTEGER; BEGIN PERFORM public.authenticate_saga_node(p_node_id,p_node_token,false,true); IF p_job_id IS NULL OR p_attempt_token IS NULL OR p_outcome NOT IN('complete','retry','manual_review') THEN RAISE EXCEPTION 'invalid recovery lease release request' USING ERRCODE='22023'; END IF; SELECT j.reconcile_attempt_count,j.max_attempts,j.recovery_backoff_seconds INTO attempts,allowed,base FROM public.transfer_jobs j WHERE j.id=p_job_id AND j.saga_version=1 AND j.direction='upload' AND j.request_spec->>'staging_node_id'=p_node_id AND j.lease_owner='recovery:'||p_node_id AND j.attempt_token=p_attempt_token FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'recovery lease is missing or fenced' USING ERRCODE='40001'; END IF; UPDATE public.transfer_jobs j SET attempt_token=NULL,lease_owner=NULL,lease_expires_at=NULL,recovery_next_attempt_at=CASE WHEN p_outcome='retry' AND attempts<allowed THEN now()+make_interval(secs=>LEAST(86400,base*(2^LEAST(attempts-1,10))::integer)) ELSE NULL END,recovery_manual_review=p_outcome='manual_review' OR (p_outcome='retry' AND attempts>=allowed),recovery_last_error=CASE WHEN p_outcome='complete' THEN NULL ELSE left(COALESCE(p_error,p_outcome),4000) END,recovery_last_error_at=CASE WHEN p_outcome='complete' THEN NULL ELSE now() END,updated_at=now() WHERE j.id=p_job_id; END $$;
REVOKE ALL ON FUNCTION public.claim_upload_saga_recovery(TEXT,TEXT,INTEGER) FROM PUBLIC; REVOKE ALL ON FUNCTION public.renew_upload_saga_recovery(TEXT,TEXT,UUID,UUID,INTEGER) FROM PUBLIC; REVOKE ALL ON FUNCTION public.release_upload_saga_recovery(TEXT,TEXT,UUID,UUID,TEXT,TEXT) FROM PUBLIC;
\getenv td_app_user POSTGRES_APP_USER
\if :{?td_app_user}
\else
\echo 'POSTGRES_APP_USER is missing from .env'
\quit 3
\endif
SELECT format('GRANT EXECUTE ON FUNCTION public.claim_upload_saga_recovery(TEXT,TEXT,INTEGER) TO %I',:'td_app_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION public.renew_upload_saga_recovery(TEXT,TEXT,UUID,UUID,INTEGER) TO %I',:'td_app_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION public.release_upload_saga_recovery(TEXT,TEXT,UUID,UUID,TEXT,TEXT) TO %I',:'td_app_user') \gexec
INSERT INTO public.schema_migrations(version) VALUES('011_upload_recovery_retry_policy') ON CONFLICT DO NOTHING;
COMMIT;
