BEGIN;
SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='120s';
CREATE OR REPLACE FUNCTION public.operator_upsert_saga_node(p_operator_id TEXT,p_operator_token TEXT,p_node_id TEXT,p_node_token TEXT,p_is_operator BOOLEAN DEFAULT false,p_metadata JSONB DEFAULT '{}'::jsonb) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN PERFORM public.authenticate_saga_node(p_operator_id,p_operator_token,true,true); IF p_node_id IS NULL OR p_node_id<>btrim(p_node_id) OR length(p_node_id) NOT BETWEEN 1 AND 128 OR p_node_token IS NULL OR length(p_node_token) NOT BETWEEN 32 AND 4096 OR p_metadata IS NULL OR jsonb_typeof(p_metadata)<>'object' THEN RAISE EXCEPTION 'invalid Saga node registration' USING ERRCODE='22023'; END IF; INSERT INTO public.saga_node_registry(node_id,token_hash,status,is_operator,metadata) VALUES(p_node_id,digest(convert_to(p_node_token,'UTF8'),'sha256'),'active',p_is_operator,p_metadata) ON CONFLICT(node_id) DO UPDATE SET token_hash=EXCLUDED.token_hash,status='active',is_operator=EXCLUDED.is_operator,metadata=EXCLUDED.metadata,drain_requested_at=NULL,disabled_at=NULL,updated_at=now(); END $$;
CREATE OR REPLACE FUNCTION public.operator_set_saga_node_status(p_operator_id TEXT,p_operator_token TEXT,p_node_id TEXT,p_status TEXT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN PERFORM public.authenticate_saga_node(p_operator_id,p_operator_token,true,true); IF p_status NOT IN('active','draining','disabled') THEN RAISE EXCEPTION 'invalid Saga node status' USING ERRCODE='22023'; END IF; IF p_operator_id=p_node_id AND p_status<>'active' THEN RAISE EXCEPTION 'operator cannot drain or disable itself' USING ERRCODE='22023'; END IF; UPDATE public.saga_node_registry SET status=p_status,drain_requested_at=CASE WHEN p_status='draining' THEN COALESCE(drain_requested_at,now()) ELSE NULL END,disabled_at=CASE WHEN p_status='disabled' THEN COALESCE(disabled_at,now()) ELSE NULL END,updated_at=now() WHERE node_id=p_node_id; IF NOT FOUND THEN RAISE EXCEPTION 'Saga node not found' USING ERRCODE='P0002'; END IF; END $$;
CREATE OR REPLACE FUNCTION public.operator_rebind_upload_saga_recovery(p_operator_id TEXT,p_operator_token TEXT,p_from_node_id TEXT,p_to_node_id TEXT,p_limit INTEGER DEFAULT 1000) RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ DECLARE moved INTEGER; BEGIN PERFORM public.authenticate_saga_node(p_operator_id,p_operator_token,true,true); IF p_from_node_id IS NULL OR p_to_node_id IS NULL OR p_from_node_id=p_to_node_id OR p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 10000 THEN RAISE EXCEPTION 'invalid Saga node rebind request' USING ERRCODE='22023'; END IF; PERFORM 1 FROM public.saga_node_registry WHERE node_id=p_from_node_id AND status IN('draining','disabled'); IF NOT FOUND THEN RAISE EXCEPTION 'source node must be draining or disabled' USING ERRCODE='55000'; END IF; PERFORM 1 FROM public.saga_node_registry WHERE node_id=p_to_node_id AND status='active'; IF NOT FOUND THEN RAISE EXCEPTION 'target node must be active' USING ERRCODE='55000'; END IF; WITH movable AS (SELECT j.id FROM public.transfer_jobs j WHERE j.saga_version=1 AND j.direction='upload' AND j.request_spec->>'staging_node_id'=p_from_node_id AND j.status IN('telegram_succeeded','compensation_pending') AND (j.attempt_token IS NULL OR j.lease_owner IS NULL OR j.lease_expires_at IS NULL OR j.lease_expires_at<=now()) ORDER BY j.created_at,j.id FOR UPDATE SKIP LOCKED LIMIT p_limit) UPDATE public.transfer_jobs j SET request_spec=jsonb_set(j.request_spec,'{staging_node_id}',to_jsonb(p_to_node_id),false),attempt_token=NULL,lease_owner=NULL,lease_expires_at=NULL,recovery_next_attempt_at=LEAST(COALESCE(j.recovery_next_attempt_at,now()),now()),updated_at=now() FROM movable WHERE j.id=movable.id; GET DIAGNOSTICS moved=ROW_COUNT; RETURN moved; END $$;
CREATE OR REPLACE FUNCTION public.operator_requeue_upload_saga_recovery(p_operator_id TEXT,p_operator_token TEXT,p_job_id UUID,p_target_node_id TEXT DEFAULT NULL,p_reset_attempts BOOLEAN DEFAULT false) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN PERFORM public.authenticate_saga_node(p_operator_id,p_operator_token,true,true); IF p_job_id IS NULL THEN RAISE EXCEPTION 'job id is required' USING ERRCODE='22023'; END IF; IF p_target_node_id IS NOT NULL THEN PERFORM 1 FROM public.saga_node_registry WHERE node_id=p_target_node_id AND status='active'; IF NOT FOUND THEN RAISE EXCEPTION 'target node must be active' USING ERRCODE='55000'; END IF; END IF; UPDATE public.transfer_jobs j SET request_spec=CASE WHEN p_target_node_id IS NULL THEN j.request_spec ELSE jsonb_set(j.request_spec,'{staging_node_id}',to_jsonb(p_target_node_id),false) END,reconcile_attempt_count=CASE WHEN p_reset_attempts THEN 0 ELSE j.reconcile_attempt_count END,recovery_manual_review=false,recovery_next_attempt_at=now(),recovery_last_error=NULL,recovery_last_error_at=NULL,attempt_token=NULL,lease_owner=NULL,lease_expires_at=NULL,updated_at=now() WHERE j.id=p_job_id AND j.saga_version=1 AND j.direction='upload' AND j.status IN('telegram_succeeded','compensation_pending') AND (j.attempt_token IS NULL OR j.lease_owner IS NULL OR j.lease_expires_at IS NULL OR j.lease_expires_at<=now()); IF NOT FOUND THEN RAISE EXCEPTION 'recovery job is missing or has an active lease' USING ERRCODE='55000'; END IF; END $$;
REVOKE ALL ON FUNCTION public.operator_upsert_saga_node(TEXT,TEXT,TEXT,TEXT,BOOLEAN,JSONB) FROM PUBLIC; REVOKE ALL ON FUNCTION public.operator_set_saga_node_status(TEXT,TEXT,TEXT,TEXT) FROM PUBLIC; REVOKE ALL ON FUNCTION public.operator_rebind_upload_saga_recovery(TEXT,TEXT,TEXT,TEXT,INTEGER) FROM PUBLIC; REVOKE ALL ON FUNCTION public.operator_requeue_upload_saga_recovery(TEXT,TEXT,UUID,TEXT,BOOLEAN) FROM PUBLIC;
\getenv td_app_user POSTGRES_APP_USER
\if :{?td_app_user}
\else
\echo 'POSTGRES_APP_USER is missing from .env'
\quit 3
\endif
SELECT format('GRANT EXECUTE ON FUNCTION public.operator_upsert_saga_node(TEXT,TEXT,TEXT,TEXT,BOOLEAN,JSONB) TO %I',:'td_app_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION public.operator_set_saga_node_status(TEXT,TEXT,TEXT,TEXT) TO %I',:'td_app_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION public.operator_rebind_upload_saga_recovery(TEXT,TEXT,TEXT,TEXT,INTEGER) TO %I',:'td_app_user') \gexec
SELECT format('GRANT EXECUTE ON FUNCTION public.operator_requeue_upload_saga_recovery(TEXT,TEXT,UUID,TEXT,BOOLEAN) TO %I',:'td_app_user') \gexec
INSERT INTO public.schema_migrations(version) VALUES('012_saga_node_drain_rebind') ON CONFLICT DO NOTHING;
COMMIT;
