-- Durable global/tenant/bot/peer scheduler. PostgreSQL is authoritative.
BEGIN;SET LOCAL lock_timeout='5s';SET LOCAL statement_timeout='120s';
CREATE TABLE IF NOT EXISTS scheduler_resources(resource_key TEXT PRIMARY KEY,resource_kind TEXT NOT NULL CHECK(resource_kind IN('global','tenant','bot','peer')),capacity INT NOT NULL DEFAULT 1 CHECK(capacity BETWEEN 1 AND 1024),active_leases INT NOT NULL DEFAULT 0 CHECK(active_leases BETWEEN 0 AND capacity),cooldown_until TIMESTAMPTZ,cooldown_reason TEXT,fence_sequence BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(resource_key LIKE resource_kind||':%'));
CREATE TABLE IF NOT EXISTS scheduler_leases(lease_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),job_id UUID NOT NULL REFERENCES transfer_jobs(id) ON DELETE CASCADE,tenant_id UUID NOT NULL REFERENCES tenants(id),node_id TEXT NOT NULL REFERENCES saga_node_registry(node_id),attempt_token UUID NOT NULL DEFAULT gen_random_uuid(),fence_token BIGINT NOT NULL CHECK(fence_token>0),resource_keys TEXT[] NOT NULL CHECK(cardinality(resource_keys) BETWEEN 2 AND 4),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','succeeded','retry_wait','dead_letter','manual_review','cancelled')),lease_expires_at TIMESTAMPTZ NOT NULL,next_attempt_at TIMESTAMPTZ,last_error_code TEXT,last_error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),finished_at TIMESTAMPTZ);
CREATE UNIQUE INDEX IF NOT EXISTS uq_scheduler_active_job ON scheduler_leases(job_id) WHERE status='active';CREATE INDEX IF NOT EXISTS idx_scheduler_expiry ON scheduler_leases(lease_expires_at) WHERE status='active';REVOKE ALL ON scheduler_resources,scheduler_leases FROM PUBLIC;
CREATE OR REPLACE FUNCTION scheduler_validate_keys(p TEXT[])RETURNS VOID LANGUAGE plpgsql IMMUTABLE AS $$DECLARE ordered TEXT[];n INT;BEGIN IF p IS NULL OR cardinality(p) NOT BETWEEN 2 AND 4 THEN RAISE EXCEPTION 'invalid scheduler keys' USING ERRCODE='22023';END IF;SELECT array_agg(k ORDER BY CASE split_part(k,':',1)WHEN'global'THEN 1 WHEN'tenant'THEN 2 WHEN'bot'THEN 3 WHEN'peer'THEN 4 ELSE 99 END,k),count(DISTINCT k)INTO ordered,n FROM unnest(p)k;IF n<>cardinality(p)OR p<>ordered OR split_part(p[1],':',1)<>'global'OR split_part(p[2],':',1)<>'tenant'OR EXISTS(SELECT 1 FROM unnest(p)k WHERE split_part(k,':',1)NOT IN('global','tenant','bot','peer'))THEN RAISE EXCEPTION 'keys must be unique ordered global tenant bot peer' USING ERRCODE='22023';END IF;END$$;
CREATE OR REPLACE FUNCTION acquire_transfer_scheduler_lease(n TEXT,t TEXT,j UUID,keys TEXT[],seconds INT DEFAULT 120)RETURNS TABLE(lease_id UUID,attempt_token UUID,fence_token BIGINT,lease_expires_at TIMESTAMPTZ)LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$DECLARE k TEXT;r scheduler_resources%ROWTYPE;tenant UUID;f BIGINT:=0;l UUID:=gen_random_uuid();a UUID:=gen_random_uuid();e TIMESTAMPTZ;BEGIN PERFORM authenticate_saga_node(n,t,false,false);PERFORM scheduler_validate_keys(keys);IF seconds NOT BETWEEN 15 AND 900 THEN RAISE EXCEPTION 'invalid lease duration' USING ERRCODE='22023';END IF;SELECT tenant_id INTO tenant FROM transfer_jobs WHERE id=j FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'job not found' USING ERRCODE='P0002';END IF;IF split_part(keys[2],':',2)<>tenant::text THEN RAISE EXCEPTION 'tenant mismatch' USING ERRCODE='42501';END IF;IF EXISTS(SELECT 1 FROM scheduler_leases x WHERE x.job_id=j AND x.status='active' AND x.lease_expires_at>now())THEN RAISE EXCEPTION 'active lease exists' USING ERRCODE='55P03';END IF;UPDATE scheduler_leases x SET status='retry_wait',next_attempt_at=now(),last_error_code='LEASE_EXPIRED',finished_at=now(),updated_at=now() WHERE x.job_id=j AND x.status='active' AND x.lease_expires_at<=now();FOREACH k IN ARRAY keys LOOP INSERT INTO scheduler_resources(resource_key,resource_kind)VALUES(k,split_part(k,':',1))ON CONFLICT DO NOTHING;SELECT*INTO r FROM scheduler_resources WHERE resource_key=k FOR UPDATE;UPDATE scheduler_resources s SET active_leases=(SELECT count(*)FROM scheduler_leases x WHERE x.status='active'AND x.lease_expires_at>now()AND s.resource_key=ANY(x.resource_keys)),updated_at=now()WHERE s.resource_key=k RETURNING*INTO r;IF r.cooldown_until>now()OR r.active_leases>=r.capacity THEN RAISE EXCEPTION 'scheduler resource unavailable: %',k USING ERRCODE='55P03';END IF;UPDATE scheduler_resources SET fence_sequence=fence_sequence+1 WHERE resource_key=k RETURNING fence_sequence INTO f;END LOOP;e:=now()+make_interval(secs=>seconds);INSERT INTO scheduler_leases(lease_id,job_id,tenant_id,node_id,attempt_token,fence_token,resource_keys,status,lease_expires_at)VALUES(l,j,tenant,n,a,f,keys,'active',e);UPDATE scheduler_resources SET active_leases=active_leases+1 WHERE resource_key=ANY(keys);RETURN QUERY SELECT l,a,f,e;END$$;
CREATE OR REPLACE FUNCTION renew_transfer_scheduler_lease(n TEXT,t TEXT,l UUID,a UUID,f BIGINT,seconds INT DEFAULT 120)RETURNS TIMESTAMPTZ LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$DECLARE e TIMESTAMPTZ;BEGIN PERFORM authenticate_saga_node(n,t,false,true);IF seconds NOT BETWEEN 15 AND 900 THEN RAISE EXCEPTION 'invalid lease duration' USING ERRCODE='22023';END IF;UPDATE scheduler_leases SET lease_expires_at=now()+make_interval(secs=>seconds),updated_at=now()WHERE lease_id=l AND node_id=n AND attempt_token=a AND fence_token=f AND status='active'AND lease_expires_at>now()RETURNING lease_expires_at INTO e;IF NOT FOUND THEN RAISE EXCEPTION 'stale lease' USING ERRCODE='55000';END IF;RETURN e;END$$;
CREATE OR REPLACE FUNCTION finish_transfer_scheduler_lease(n TEXT,t TEXT,l UUID,a UUID,f BIGINT,outcome TEXT,ec TEXT DEFAULT NULL,em TEXT DEFAULT NULL,retry_seconds INT DEFAULT NULL)RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$DECLARE keys TEXT[];s TEXT;BEGIN PERFORM authenticate_saga_node(n,t,false,true);IF outcome NOT IN('success','retry','dead_letter','manual_review','cancelled')OR(outcome='retry'AND retry_seconds NOT BETWEEN 1 AND 86400)THEN RAISE EXCEPTION 'invalid outcome' USING ERRCODE='22023';END IF;s:=CASE outcome WHEN'success'THEN'succeeded'WHEN'retry'THEN'retry_wait'ELSE outcome END;UPDATE scheduler_leases SET status=s,next_attempt_at=CASE WHEN outcome='retry'THEN now()+make_interval(secs=>retry_seconds)END,last_error_code=left(ec,128),last_error_message=left(em,2048),finished_at=now(),updated_at=now()WHERE lease_id=l AND node_id=n AND attempt_token=a AND fence_token=f AND status='active'RETURNING resource_keys INTO keys;IF NOT FOUND THEN RAISE EXCEPTION 'stale lease' USING ERRCODE='55000';END IF;UPDATE scheduler_resources r SET active_leases=(SELECT count(*)FROM scheduler_leases x WHERE x.status='active'AND x.lease_expires_at>now()AND r.resource_key=ANY(x.resource_keys)),updated_at=now()WHERE r.resource_key=ANY(keys);RETURN s;END$$;
CREATE OR REPLACE FUNCTION set_transfer_scheduler_cooldown(n TEXT,t TEXT,k TEXT,seconds INT,reason TEXT)RETURNS TIMESTAMPTZ LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$DECLARE e TIMESTAMPTZ;BEGIN PERFORM authenticate_saga_node(n,t,false,true);IF seconds NOT BETWEEN 1 AND 86400 OR split_part(k,':',1)NOT IN('global','tenant','bot','peer')THEN RAISE EXCEPTION 'invalid cooldown' USING ERRCODE='22023';END IF;e:=now()+make_interval(secs=>seconds);INSERT INTO scheduler_resources(resource_key,resource_kind,cooldown_until,cooldown_reason)VALUES(k,split_part(k,':',1),e,left(reason,512))ON CONFLICT(resource_key)DO UPDATE SET cooldown_until=greatest(coalesce(scheduler_resources.cooldown_until,'-infinity'),excluded.cooldown_until),cooldown_reason=excluded.cooldown_reason,updated_at=now()RETURNING cooldown_until INTO e;RETURN e;END$$;
REVOKE ALL ON FUNCTION scheduler_validate_keys(TEXT[]),acquire_transfer_scheduler_lease(TEXT,TEXT,UUID,TEXT[],INT),renew_transfer_scheduler_lease(TEXT,TEXT,UUID,UUID,BIGINT,INT),finish_transfer_scheduler_lease(TEXT,TEXT,UUID,UUID,BIGINT,TEXT,TEXT,TEXT,INT),set_transfer_scheduler_cooldown(TEXT,TEXT,TEXT,INT,TEXT)FROM PUBLIC;
\getenv td_app_user POSTGRES_APP_USER
\if :{?td_app_user}
\else
\echo 'POSTGRES_APP_USER is missing from .env'
\quit 3
\endif
SELECT format('GRANT EXECUTE ON FUNCTION acquire_transfer_scheduler_lease(TEXT,TEXT,UUID,TEXT[],INT) TO %I',:'td_app_user')\gexec
SELECT format('GRANT EXECUTE ON FUNCTION renew_transfer_scheduler_lease(TEXT,TEXT,UUID,UUID,BIGINT,INT) TO %I',:'td_app_user')\gexec
SELECT format('GRANT EXECUTE ON FUNCTION finish_transfer_scheduler_lease(TEXT,TEXT,UUID,UUID,BIGINT,TEXT,TEXT,TEXT,INT) TO %I',:'td_app_user')\gexec
SELECT format('GRANT EXECUTE ON FUNCTION set_transfer_scheduler_cooldown(TEXT,TEXT,TEXT,INT,TEXT) TO %I',:'td_app_user')\gexec
INSERT INTO schema_migrations(version)VALUES('014_durable_transfer_scheduler')ON CONFLICT DO NOTHING;COMMIT;